survey_car:
    resource: "@SurveyCarBundle/Resources/config/routing.yml"
    prefix:   /car

app:
    resource: '@AppBundle/Controller/'
    type: annotation
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"