<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container2nlxkxf\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container2nlxkxf/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container2nlxkxf.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\Container2nlxkxf\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \Container2nlxkxf\appDevDebugProjectContainer(array(
    'container.build_hash' => '2nlxkxf',
    'container.build_id' => 'b345102b',
    'container.build_time' => 1532698139,
), __DIR__.\DIRECTORY_SEPARATOR.'Container2nlxkxf');
